### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by 0xspade** [LINKIWI/orion-server#16]
Any updates from here? you should have a donation button at least or continue with the docker and let's see who will donate and then maintain this project. it has a potential for the open-source community. work with nexttracks rather than owntrack btw.

**Comment by LINKIWI** [comment]
I don't accept donations because I build my projects purely for my own use, but make them public on a "source available" basis. Donations represent a monetary incentive to steer the project in a direction that I might not need for my own use.

I've archived this repository to move it into a read-only state since this repository will not receive any more updates. (I've since migrated to a new solution which is not open source.)
